import {defineField, defineType} from 'sanity'

const sourceOptions = [
  {title: 'Contacto', value: 'contact'},
  {title: 'Catálogo', value: 'catalogue'},
  {title: 'Produto', value: 'product'},
  {title: 'Caso de estudo', value: 'case'},
  {title: 'Blog', value: 'blog'},
  {title: 'Outro', value: 'unknown'},
]

const statusOptions = [
  {title: 'Novo', value: 'new'},
  {title: 'Lido', value: 'read'},
  {title: 'Em acompanhamento', value: 'inProgress'},
  {title: 'Resolvido', value: 'resolved'},
  {title: 'Spam', value: 'spam'},
  {title: 'Arquivado', value: 'archived'},
]

export const formSubmission = defineType({
  name: 'formSubmission',
  title: 'Pedido recebido',
  type: 'document',
  groups: [
    {name: 'request', title: 'Pedido', default: true},
    {name: 'client', title: 'Cliente'},
    {name: 'management', title: 'Gestão'},
    {name: 'security', title: 'Segurança'},
  ],
  fields: [
    defineField({
      name: 'submittedAt',
      title: 'Recebido em',
      type: 'datetime',
      group: 'request',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'source',
      title: 'Origem do pedido',
      type: 'string',
      group: 'request',
      readOnly: true,
      options: {list: sourceOptions, layout: 'radio'},
    }),
    defineField({
      name: 'sourcePath',
      title: 'Página de origem',
      type: 'string',
      group: 'request',
      readOnly: true,
    }),
    defineField({
      name: 'language',
      title: 'Idioma usado',
      type: 'string',
      group: 'request',
      readOnly: true,
      options: {
        list: [
          {title: 'Português', value: 'pt'},
          {title: 'Inglês', value: 'en'},
          {title: 'Espanhol', value: 'es'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'message',
      title: 'Mensagem',
      type: 'text',
      rows: 7,
      group: 'request',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'profile',
      title: 'Perfil de cliente',
      type: 'reference',
      to: [{type: 'clientProfile'}],
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'name',
      title: 'Nome',
      type: 'string',
      group: 'client',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'email',
      group: 'client',
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'phone',
      title: 'Telefone',
      type: 'string',
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'address',
      title: 'Morada',
      type: 'string',
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'postalCode',
      title: 'Código postal',
      type: 'string',
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'locality',
      title: 'Localidade',
      type: 'string',
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'marketingConsent',
      title: 'Aceitou contacto comercial/marketing',
      type: 'boolean',
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'consentText',
      title: 'Texto de consentimento aceite',
      type: 'text',
      rows: 3,
      group: 'client',
      readOnly: true,
    }),
    defineField({
      name: 'status',
      title: 'Estado',
      type: 'string',
      group: 'management',
      initialValue: 'new',
      options: {list: statusOptions, layout: 'radio'},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'internalNotes',
      title: 'Notas internas',
      description: 'Notas de acompanhamento. Nunca aparecem no website.',
      type: 'text',
      rows: 4,
      group: 'management',
    }),
    defineField({
      name: 'requestId',
      title: 'ID técnico do pedido',
      type: 'string',
      group: 'security',
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'emailHash',
      title: 'Hash do email',
      type: 'string',
      group: 'security',
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'phoneHash',
      title: 'Hash do telefone',
      type: 'string',
      group: 'security',
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'ipHash',
      title: 'Hash do IP',
      type: 'string',
      group: 'security',
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'userAgent',
      title: 'Navegador',
      type: 'string',
      group: 'security',
      hidden: true,
      readOnly: true,
    }),
  ],
  orderings: [
    {
      title: 'Mais recentes primeiro',
      name: 'submittedAtDesc',
      by: [{field: 'submittedAt', direction: 'desc'}],
    },
  ],
  preview: {
    select: {
      title: 'name',
      email: 'email',
      source: 'source',
      status: 'status',
      submittedAt: 'submittedAt',
    },
    prepare({title, email, source, status, submittedAt}) {
      const date = submittedAt ? new Date(submittedAt).toLocaleDateString('pt-PT') : 'sem data'
      return {
        title: title || email || 'Pedido sem nome',
        subtitle: `${date} · ${source || 'unknown'} · ${status || 'new'} · ${email || 'sem email'}`,
      }
    },
  },
})
