import {defineField, defineType} from 'sanity'

export const productCategory = defineType({
  name: 'productCategory',
  title: 'Produto',
  type: 'document',
  groups: [
    {name: 'conteudo', title: 'Conteúdo', default: true},
    {name: 'imagens', title: 'Imagens'},
    {name: 'organizacao', title: 'Organização'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nome do produto',
      description: 'Nome público da solução.',
      type: 'localizedString',
      group: 'conteudo',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Endereço da página',
      description: 'Gere a partir do nome e evite alterar depois de publicar.',
      type: 'slug',
      group: 'conteudo',
      options: {source: 'title.pt', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'image',
      title: 'Imagem principal',
      description: 'Usada na listagem e na página do produto.',
      type: 'image',
      group: 'imagens',
      options: {hotspot: true},
      fields: [
        defineField({
          name: 'alt',
          title: 'Descrição da imagem',
          description: 'Para acessibilidade. Diga o que se vê.',
          type: 'localizedString',
          validation: (Rule) => Rule.required().warning('Adicione uma descrição para leitores de ecrã.'),
        }),
      ],
    }),
    defineField({
      name: 'gallery',
      title: 'Galeria',
      description: 'Imagens e vídeos adicionais.',
      type: 'array',
      group: 'imagens',
      of: [
        defineField({
          name: 'galleryImage',
          title: 'Imagem da galeria',
          type: 'image',
          options: {hotspot: true},
          fields: [
            defineField({
              name: 'alt',
              title: 'Descrição da imagem',
              description: 'Para acessibilidade. Diga o que se vê.',
              type: 'localizedString',
              validation: (Rule) => Rule.required().warning('Adicione uma descrição para leitores de ecrã.'),
            }),
          ],
        }),
        defineField({
          name: 'galleryVideo',
          title: 'Vídeo carregado',
          description: 'Ficheiro de vídeo para aparecer na galeria da página do produto.',
          type: 'file',
          options: {
            accept: 'video/mp4,video/webm,video/quicktime',
          },
          fields: [
            defineField({
              name: 'title',
              title: 'Título do vídeo',
              description: 'Identifica o vídeo no player.',
              type: 'localizedString',
            }),
            defineField({
              name: 'poster',
              title: 'Imagem de capa',
              description: 'Opcional. Aparece antes da reprodução.',
              type: 'image',
              options: {hotspot: true},
              fields: [
                defineField({
                  name: 'alt',
                  title: 'Descrição da imagem',
                  description: 'Para acessibilidade. Diga o que se vê.',
                  type: 'localizedString',
                  validation: (Rule) => Rule.required().warning('Adicione uma descrição para leitores de ecrã.'),
                }),
              ],
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'summary',
      title: 'Resumo',
      description: 'Explique rapidamente onde a solução é útil.',
      type: 'localizedText',
      group: 'conteudo',
    }),
    defineField({
      name: 'description',
      title: 'Descrição',
      description: 'Texto principal da página.',
      type: 'localizedText',
      group: 'conteudo',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Vídeo do produto',
      description: 'Opcional. Cole o link do vídeo no YouTube.',
      type: 'url',
      group: 'conteudo',
    }),
    defineField({
      name: 'videoTitle',
      title: 'Título do vídeo',
      description: 'Legenda do vídeo e texto para leitores de ecrã.',
      type: 'localizedString',
      group: 'conteudo',
    }),
    defineField({
      name: 'toolUrl',
      title: 'Link da ferramenta',
      description: 'Opcional. Simulador, calculadora ou configurador.',
      type: 'url',
      group: 'conteudo',
    }),
    defineField({
      name: 'toolTitle',
      title: 'Título da ferramenta',
      description: 'Título mostrado junto ao link.',
      type: 'localizedString',
      group: 'conteudo',
    }),
    defineField({
      name: 'toolText',
      title: 'Descrição da ferramenta',
      description: 'Explique o que a pessoa pode fazer.',
      type: 'localizedText',
      group: 'conteudo',
    }),
    defineField({
      name: 'toolLabel',
      title: 'Texto do botão da ferramenta',
      description: 'Exemplo: “Construir o meu deck”.',
      type: 'localizedString',
      group: 'conteudo',
    }),
    defineField({
      name: 'orderRank',
      title: 'Ordem de apresentação',
      description: 'O número mais baixo aparece primeiro.',
      type: 'number',
      group: 'organizacao',
      initialValue: 100,
    }),
  ],
  preview: {
    select: {
      title: 'title.pt',
      subtitle: 'summary.pt',
      media: 'image',
    },
  },
})
