// Right-sized, modern-format images from the Sanity CDN.
//
// Every served variant uses a deterministic `fm=webp` URL at one of a small,
// fixed set of widths (WIDTH_STEPS). Because the set is fixed and the format is
// forced (not negotiated via the Accept header), the exact URLs the browser
// requests can be pre-generated by scripts/warm-images.ts — so visitors never
// hit a cold, slow-to-generate transform. Non-Sanity URLs pass through.

export const WIDTH_STEPS = [160, 320, 400, 640, 900, 1100, 1600, 2000]

const isSanityCdn = (url: string) => url.includes('cdn.sanity.io')

const snap = (width: number) =>
  WIDTH_STEPS.find((step) => step >= width) ?? WIDTH_STEPS[WIDTH_STEPS.length - 1]

const variant = (url: string, width: number, quality: number) => {
  const separator = url.includes('?') ? '&' : '?'
  return `${url}${separator}w=${width}&q=${quality}&fm=webp&fit=max`
}

export const sizedImage = (url: string | undefined, width = 900, quality = 72) => {
  if (!url || !isSanityCdn(url)) return url ?? ''
  return variant(url, snap(width), quality)
}

export const imageSrcset = (
  url: string | undefined,
  widths: number[],
  quality = 72,
): string | undefined => {
  if (!url || !isSanityCdn(url) || !widths.length) return undefined
  const maxStep = snap(Math.max(...widths))
  const steps = WIDTH_STEPS.filter((step) => step <= maxStep)
  return steps.map((step) => `${variant(url, step, quality)} ${step}w`).join(', ')
}
